name: new_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  intl: ^0.19.0
  page_route_animator: ^1.0.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  image_picker: ^1.0.7
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  chewie: ^1.7.4
  video_player: ^2.8.2
  share_plus: ^7.2.2
  provider: ^6.0.4
  google_sign_in: ^6.2.1
  email_auth: ^1.1.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/Icons/
    - assets/Images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
