// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMoTknrEa6-nAm6ntSP53FRC-UNe3Xcy0',
    appId: '1:257891899504:web:39d235eeefd15b4750fcb5',
    messagingSenderId: '257891899504',
    projectId: 'newproject-9ec3c',
    authDomain: 'newproject-9ec3c.firebaseapp.com',
    storageBucket: 'newproject-9ec3c.appspot.com',
    measurementId: 'G-G69PP69GD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AU6Sjp1alSzODmrzPCQDsGwna2xl2mg',
    appId: '1:257891899504:android:ed9432077ceffa3150fcb5',
    messagingSenderId: '257891899504',
    projectId: 'newproject-9ec3c',
    storageBucket: 'newproject-9ec3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5E7LxHWOiYV0SW8jaaq08Mpq_OtdSKh0',
    appId: '1:257891899504:ios:69fc55008291882750fcb5',
    messagingSenderId: '257891899504',
    projectId: 'newproject-9ec3c',
    storageBucket: 'newproject-9ec3c.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5E7LxHWOiYV0SW8jaaq08Mpq_OtdSKh0',
    appId: '1:257891899504:ios:0db182312b0a137a50fcb5',
    messagingSenderId: '257891899504',
    projectId: 'newproject-9ec3c',
    storageBucket: 'newproject-9ec3c.appspot.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
